name: scale_module
description: A new Flutter module project.

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  get: ^4.6.5
  unicons: ^2.1.1
  diabetes_models:
    git: 
      url: git@github.com:niypoo/diabetes_models.git
  diabetes_helpers:
    git: 
      url: git@github.com:niypoo/diabetes_helpers.git
  diabetes_enums:
    git: 
      url: git@github.com:niypoo/diabetes_enums.git
  fly_ui:
    git: https://github.com/niypoo/fly_ui.git
  app_configuration_service:
    git: https://github.com/niypoo/app_configuration_service.git
  # ruler_picker:
  #   path: ../../../../modules/ruler_picker
  bottom_sheet_helper:
    git: https://github.com/niypoo/bottom_sheet_helper.git

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0